project:
  name: quickstart-cloud9-ide
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-2
    - us-east-1
    - us-west-2
    - ap-southeast-1
    - ap-northeast-1
    - eu-central-1
    - eu-west-1
  s3_bucket: ''
tests:
  c9:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-cloud9-ide/
      BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 0.0.0.0/0
    regions:
      - us-east-2
      - us-east-1
      - us-west-2
      - ap-southeast-1
      - ap-northeast-1
      - eu-central-1
      - eu-west-1
    s3_bucket: ''
    template: templates/cloud9-ide-master.template.yaml
